export {Arrow} from './Arrow'
export {ClassOf} from './ClassOf'
export {Composer, Composed} from './Compose'
export {Curry} from './Curry'
export {ParamsOf} from './ParamsOf'
export {Piper, Piped} from './Pipe'
export {ReturnOf} from './ReturnOf'
// export {UnCurry} from './UnCurry'
