export {Arrow} from './Arrow'
export {ClassOf} from './ClassOf'
export {Composer, Compose} from './Compose'
export {Gap, Curry} from './Curry'
export {ParamsOf} from './ParamsOf'
export {Piper, Pipe} from './Pipe'
export {ReturnOf} from './ReturnOf'
// export {UnCurry} from './UnCurry'
